### ISSUE TITLE
Missing comma

### ISSUE THREAD

**Issue by iketari** [OnwerkGmbH/node-versioneye-update#10]
Missing comma in https://github.com/OnwerkGmbH/node-versioneye-update/blob/master/lib/constants.js

after  'yarn.lock'

```
        'package.json', // NPM (Node.JS)
        'yarn.lock' // Yarn (Node.JS)
        'bower.json', // Bower (JavaScript)
```

**Comment by jdoose** [comment]
Thanks for the issue! It is fixed now, you can use version 1.4.3
