### ISSUE TITLE
On enterprise servers there seems no way to supply the organisation

### ISSUE THREAD

**Issue by sruehl** [OnwerkGmbH/node-versioneye-update#16]
Using this plugin with an enterprise server does result in an error:
`VersionEye API says:
{ error: 'ERROR. Organisation is not defined or you do not have access to it!' }
Error: VersionEye API says "ERROR. Organisation is not defined or you do not have access to it!"`

I don't see any way to supply the organsiation. How is this done?

My call looks like this: `versioneye-update --dump --apikey XXXXX --baseurl XXX.XXX.XXX --createproject`

(With maven it works for me so Im excepting to supply the organisation as a parameter in a similar way)

**Comment by reiz** [comment]
Hi @sruehl. Are you using the API key from the organisation from the enterprise instance? Or are you using your personal API key? /cc @MaChristmann @jdoose

**Comment by reiz** [comment]
@sruehl I would be surprised if it doesn't work, because I know that SAP is using it since months successfully. So it's either an configuration issue or related to the newest version of this module.

**Comment by MaChristmann** [comment]
@sruehl You can also make sure your file, API key and project visibility are correct by testing them on the API site of your Versioneye Enterprise (Similar to the versioneye.com API site https://www.versioneye.com/api/#!/projects/postProjects) 

All you need to do is 
* Choose your project file
* Enter the API Key
* Click on "Try it out"

With this set of parameters you are simulating the exact same behaviour, that the node-versioneye-update is doing right now
* All the other fields are not mandatory or already have a default value

**Comment by sruehl** [comment]
@reiz Currently Im using my personal API-Key of the enterprise instance. Im able to create reports with the [versioneye_maven_plugin](https://github.com/versioneye/versioneye_maven_plugin).
So currently I try to use the npm plugin in a similar fashion than the maven-plugin.
@MaChristmann I checked with the maven plugin that in general im able to post. Also im owner of the Org unit im trying to push to. What I don't get is how the npm plugin select the organistation as this is a mandatory parameter when working with the maven plugin.

**Comment by sruehl** [comment]
ok @reiz gave the right hint.
My error was using my personal api-key instead of the organisation API-KEY. For the maven-plugin this is no problem as I have a way to supply the org.

**Comment by MaChristmann** [comment]
@reiz is this use case "Personal API key + Orga Name" intended? In that case the module needs to be extended to accept an Orga Name

**Comment by reiz** [comment]
@sruehl @MaChristmann to use the API with the personal API key is kind of legacy. Every organisation has 2 API keys. A read/write API key and read only API key. I recommend to use the read/write API key from the organisation to create/update projects. If you use the orga API key, the server can find the corresponding organisation automatically. If you are using your personal API key you have to tell the server to which organisation you want to attach the project.
