### ISSUE TITLE
Breaking Change in the API

### ISSUE THREAD

**Issue by reiz** [OnwerkGmbH/node-versioneye-update#3]
There is a little breaking change in the API. ProjectKey was completely removed and replaced through ProjectID. See here: http://blog.versioneye.com/2015/12/11/api-breaking-change-project_key-project_id/ 
Please adjust the implementation. /cc @MaChristmann

**Comment by MaChristmann** [comment]
Fortunately node-versioneye-update is only using projectID so there is no need for any further actions.

**Comment by reiz** [comment]
Very good :+1:
