### ISSUE TITLE
License and security check

### ISSUE THREAD

**Issue by reiz** [OnwerkGmbH/node-versioneye-update#5]
Would be good to have a goal for licenseCheck. If you update an existing project with a new file the JSON response object contains an attribute `licenses_red`. If the value of that attribute is greater than 0 that means that some dependencies violate your license whitelist. In that case the plugin should exit with an non 0 exit code. That way it would break the build on a CI server, in case of a license violation. 

The [VersionEye Maven Plugin](https://github.com/versioneye/versioneye_maven_plugin#mvn-versioneyelicensecheck) is doing and that way and other Plugins for Scala/SBT and Groovy/Gradle as well. Would be cool if this NPM module would support the same feature ;) /cc @MaChristmann

**Comment by jdoose** [comment]
Ok, I see the need.
If we do it we would only implement it with a special command line flag to signal that licenses should be checked. If this flag is not set the tool should only emit a warning that a license was violated

**Comment by jdoose** [comment]
Implementing this feature right now.
@reiz :  Regarding the security check: Is it ok to check the attribute `sv_count` for the number of security violations?

**Comment by reiz** [comment]
@jdoose Yes. That's the way to go :-)

**Comment by jdoose** [comment]
Done with version 1.2

**Comment by reiz** [comment]
@jdoose You guys are awesome! I just pusht it today on Twitter, FB, G+, LinkedIn and XING!
