### ISSUE TITLE
1.2.1 fails under *ix due to windows style line breaks

### ISSUE THREAD

**Issue by jdoose** [OnwerkGmbH/node-versioneye-update#7]
The current version 1.2.1 fails under unix system like ubuntu due to windows style line breaks with the error message 
 `: No such file or directory`

If `/usr/lib/node_modules/versioneye-update/bin/versioneye-update` is treated by `dos2unix` it works.

The current version contains a broken `bin/versioneye-update` file.

**Comment by MaChristmann** [comment]
Released 1.2.2
